#!/bin/sh

echo "2" > /sys/class/gpio/export
echo "3" > /sys/class/gpio/export
echo "4" > /sys/class/gpio/export

echo "out" > /sys/class/gpio/gpio2/direction
echo "out" > /sys/class/gpio/gpio3/direction
echo "in" > /sys/class/gpio/gpio4/direction

echo "1" > /sys/class/gpio/gpio2/value
echo "1" > /sys/class/gpio/gpio3/value

# fonction de clignotement des leds
cligno () {
    while true; do
        echo "1" > /sys/class/gpio/gpio2/value
	echo "0" > /sys/class/gpio/gpio3/value
        sleep 1
        echo "1" > /sys/class/gpio/gpio3/value
        echo "0" > /sys/class/gpio/gpio2/value
        sleep 1
    done
}

name=""
pass=""

while true; do
    # execute a l'appuie du bouton
    if [ $(cat /sys/class/gpio/gpio4/value) -eq 0 ]; then
    # fonction cligno en background
        cligno &
        # Se connecter et enregistrer la page
        curl -c /tmp/cookies -d "name=$name&pass=$pass&form_id=user_login&op=Se+connecter" http://lebib.org/user -s
        curl -b /tmp/cookies http://lebib.org --output /tmp/bib.html -s
        # recuperation du token et etat
        token=$(cat /tmp/bib.html | grep -m 1 form_token | awk '{print $4}' | awk -F '\"' '{print $2}')
        id=$(cat /tmp/bib.html | grep -m 1 form_build_id | awk '{print $29}' | awk -F '\"' '{print $2}')
        state=$(cat /tmp/bib.html | grep -m 1 bibopen | awk '{print $9}' | awk -F '\"' '{print $2}')
        # stock l'etat actuel
        if [ -z $state ]; then
            state=1
        else
            state=0
        fi
        # changer l'etat
        curl -b /tmp/cookies -d "op=Changer&form_build_id=$id&form_token=$token&form_id=bibstate_toggle_form" http://lebib.org -s
        # kill le dernier jobs
        kill %+
        # Si le bib est fermé allumer led orange, si ouvert allumer led blanche
        if [ $state -eq 1 ]; then
            echo -e 'USER bibuton 0 bibuton : bibuton\nNICK bibuton\nJOIN #discutoire\nTOPIC #discutoire :Le bib est ouvert \nQUIT' | nc irc.lebib.org 6667
            echo "1" > /sys/class/gpio/gpio3/value
            echo "0" > /sys/class/gpio/gpio2/value
        else
            echo -e 'USER bibuton 0 bibuton : bibuton\nNICK bibuton\nJOIN #discutoire\nTOPIC #discutoire :Le bib est fermé \nQUIT' | nc irc.lebib.org 6667
            echo "1" > /sys/class/gpio/gpio2/value
            echo "0" > /sys/class/gpio/gpio3/value
        fi
    else
        continue
    fi
done
